buzzfeed/sso

README.md

RFR @loganmeetsworld @shrayolacrayon

docs: update README for consistency

---

README.md

Updating the README with the blog post link.
cc @buzzfeed/infra-security

sso: update README to include blog post link

---

.circleci/config.yml

Fixes issues introduced in #53

circle: fix issues with circle script checking for owner

---

internal/pkg/aead/aead.go

Reverts buzzfeed/sso#51
We want to wait to land these changes until after we have an improved UX flow in https://github.com/buzzfeed/sso/pull/57

Revert "internal/pkg/aead: use base64.URLRawEncoding"

---

quickstart/kubernetes/demo-apps/hello-world-deployment.yml
quickstart/kubernetes/demo-apps/hello-world-svc.yml
quickstart/kubernetes/demo-apps/httpbin-deployment.yml
quickstart/kubernetes/demo-apps/httpbin-svc.yml
quickstart/kubernetes/sso-auth-deployment.yml
quickstart/kubernetes/sso-auth-svc.yml
quickstart/kubernetes/sso-ingress.yml
quickstart/kubernetes/sso-proxy-deployment.yml
quickstart/kubernetes/sso-proxy-svc.yml
quickstart/kubernetes/upstream-configs-configmap.yml

Lack of Kubernetes example yamls
Provide working Kubernetes yamls
I wrote a whole guide on this here - https://medium.com/@while1eq1/single-sign-on-for-internal-apps-in-kubernetes-using-google-oauth-sso-2386a34bc433

Add Kubernetes examples

---

internal/auth/static_files.go

Hi,
I think it's all detailed in this issue https://github.com/buzzfeed/sso/issues/90
I hope that helps

Fix issue 90 Use -f on statik generate comment

---

quickstart/docker-compose.yml
quickstart/kubernetes/sso-auth-deployment.yml
quickstart/kubernetes/sso-proxy-deployment.yml

quickstart: move to sso-dev:latest tag

quickstart: move to sso-dev:latest tag

---

docs/quickstart.md

Fixes minor typo in docs/quickstart.md

Typo fix in quickstart.md

---

Godeps

Godeps: remove unused dependencies

---

README.md

Seeking feedback from the community, to understand how we're doing and help to plan our roadmap!

Add community survey link to the README.

---

internal/pkg/sessions/cookie_store.go

The `SecretBytes` function appears to be unused.
Delete the code.
Fixes #144

This code appears to be unused

---

internal/proxy/oauthproxy.go
internal/proxy/oauthproxy_test.go
internal/proxy/options.go
internal/proxy/proxy_config.go
internal/proxy/proxy_config_test.go

We have the need to specify default allowed groups
Allow us to specify default allowed groups via env config for every upstream.
Needs some tests.

proxy: default allowed groups

---

Makefile

It's not immediately obvious how to push a release to docker.
Add a command to the makefile.

sso: makefile releasepush

---

.circleci/config.yml
internal/auth/authenticator.go
internal/auth/authenticator_test.go
internal/auth/mux_test.go
internal/auth/options.go
internal/auth/options_test.go
internal/auth/providers/google.go
internal/auth/providers/google_test.go
internal/auth/providers/okta.go
internal/auth/providers/okta_test.go

There is a ton of non-useful, unusable, or crufty configuration leftover in sso auth. This is an attempt to clean up the cruft configs.

authenticator: remove misc/cruft configuration

---

internal/auth/authenticator_test.go
internal/auth/configuration.go
internal/auth/options.go
internal/auth/providers/google.go
internal/auth/providers/google_test.go
internal/auth/providers/provider_data.go
internal/auth/providers/provider_default.go

Updates the version of some of the google provider endpoints + some generic google provider cleanups.

auth: update google version endpoints

---

internal/auth/authenticator_test.go
quickstart/docker-compose.yml
quickstart/kubernetes/sso-auth-deployment.yml
quickstart/kubernetes/sso-proxy-deployment.yml

Resolves https://github.com/buzzfeed/sso/issues/234 by removing the documentation references.

bug: remove auth code secret

---

Makefile
scripts/dist.sh

Bumps version to `2.1.0` for new release

sso_*: 2.1.0 release version bump

---

.circleci/config.yml
.github/release-drafter.yml
CONTRIBUTING.md
README.md
docs/okta_provider_setup.md
docs/sso_authenticator_config.md
docs/sso_config.md

The primary branch is named `master`, which is problematic.
Rename that branch to be `main`. This PR updates related references in preparation of the actual rename here in GitHub.

change 'master' references to 'main'.

---

Makefile

Please describe the problem this PR will solve.
What is the proposed solution?
Other pertinent information. Examples: a walkthrough of how the solution might work, why this solution is optimal compared to other possible solutions, or further TODOs beyond this PR.

update makefile to use newer buildx syntax

---

Makefile
docs/sso_authenticator_config.md
docs/sso_proxy_config.md
internal/pkg/sessions/cookie_store.go
internal/pkg/sessions/cookie_store_test.go
scripts/dist.sh

Reverts buzzfeed/sso#329
matches https://github.com/buzzfeed/mono/pull/74585

Revert "sessions pkg: omit domain attribute in session cookie"
