- Dockerfile
- Godeps
This results in a minimal final image without the full golang runtime, addressing #20.
RFR @loganmeetsworld @shrayolacrayon 
cc @danbf
> docker: switch to multistage build

- Makefile
- scripts/dist.sh
This adds a Makefile that we can use to run the dist.sh script in order to create tars of the binaries for releases. 
cc @buzzfeed/infra-security
> sso: makefile and dist.sh 

- internal/auth/authenticator.go
If the options funcs should error out the loop returns earlier than
expected thus putting the application in a bad state for storing
cookies.
> Check error on setting cookie store

- internal/pkg/aead/aead.go
Sporadically, we are getting a `"cipher: message authentication failed"` error which might be related to the additional padding added to the encrypted session state, that comes with using `base64.URLEncoding`.
Use `base64.RawURLEncoding`, which omits padding characters when encoding the encrypted session state.
> internal/pkg/aead: use base64.URLRawEncoding

- .circleci/config.yml
- Makefile
Currently, outside collaborators' circle builds are breaking because of the `imagepush` command.
Depend on an env present to run the command, otherwise skip it.
> circle: limit imagepush to project owners

- .gitignore
Currently the `dist/` directory created by `make` isn't in `.gitignore` but it probably should be.
> Don't check in the dist/ directory created by make

- docs/google_provider_setup.md
Docs show the ENV vars as:
BUZZFEED_GOOGLE_ADMIN_EMAIL
BUZZFEED_GOOGLE_SERVICE_ACCOUNT_JSON
when they should be:
GOOGLE_ADMIN_EMAIL
GOOGLE_SERVICE_ACCOUNT_JSON
list them in the docs as:
GOOGLE_ADMIN_EMAIL
GOOGLE_SERVICE_ACCOUNT_JSON
> ENV vars exclude BUZZFEED_ prefix

- internal/auth/authenticator.go
We identified a strange bug in our routing logic in which the `/ping` endpoint was getting a `404` **_if and only if_** we used the configured host in the request. So any requests that used any other host responded with a `200` :bug:.
This is a result of the way we've set up our mux in combination with go's default mux handling. Patterns that match a `host` domains take precedent, so when the mux receives the request with the host we've configured, it walks down the mux subtree that matched with the host and `404`'s since we haven't set up a handler for `/ping` in that mux subtree.
However, if we use a host that is not configured, the pattern does not match on the `host` domain and falls into our catchall which we've configured to respond to `/ping` requests.
We configure `/ping` on the …
> cop_auth: host domain should respond to ping

- internal/auth/authenticator.go
- internal/pkg/aead/aead.go
- internal/pkg/sessions/cookie_store.go
- internal/pkg/sessions/cookie_store_test.go
- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
It is occasionally necessary to modify the session encoding, either as improvements are made or we want to rotate secrets.
When this occurs, since each upstream session is invalidated, it creates an unpleasant user experience where a user gets a `500` on each initial visit to every upstream.
This poor ux adds unnecessary resistance to updating or modifying the session encoding. While schema changes and/or secret rotations should be taken lightly, we should be confident to make those changes with as minimal impact to UX as possible.
Instead of rendering a `500` error in loading an invalid session, we should trigger the start of a new OAuth flow. Our implicit login mechanism should mask this error for most applications and users should be seamlessly re-logged in.
This will not work for all …
> proxy: manage session failure with restart of oauth flow

- Godeps
- internal/pkg/aead/aead.go
This updates the godeps to use miscreant-go as miscreant/go was moved there. 
cc @buzzfeed/sso-maintainers
> Godeps: update miscreant repo

- internal/proxy/oauthproxy.go
- internal/proxy/proxy_config.go
- internal/proxy/proxy_config_test.go
We're investigating some reports of latency potentially introduced by the proxy.  We don't have great timing metrics isolated around the reverse proxy.
I'd like to add more metrics around the reverse proxy specifically in an attempt to narrow down what's introducing the latency.
We have overhead metrics as well as overall latency metrics, and while useful, they don't report on the latency of upstreams themselves.
> sso: add metrics to reverse proxy

- docs/quickstart.md
This adds a link to the kubernetes blog post and example to the quickstart guide. 
cc @buzzfeed/sso-maintainers
> quickstart: add link to kubernetes blog post and example

- internal/pkg/aead/aead.go
This makes the aead errors more useful and descriptive.
cc @buzzfeed/sso-maintainers
> aead: add more useful errors

- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
XHR error handling was creating obscure corner cases due to some bugs in the request flow.
Improve logging to better note handling of these requests as well as fix a bug in the request flow.
> proxy: logging handling/logging of oauth start on xml requests

- internal/pkg/aead/aead.go
- internal/pkg/aead/aead_test.go
This adds an explicit concurrency test case for aead/miscreant to test for potential data races in the underlying cipher implementation.
> pkg/aead: add explicit data race and locking to resolve

- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
- internal/auth/options.go
- internal/auth/options_test.go
- internal/pkg/aead/aead_test.go
- internal/pkg/sessions/cookie_store.go
- internal/pkg/sessions/cookie_store_test.go
- internal/pkg/sessions/session_state_test.go
- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
- internal/proxy/options.go
- internal/proxy/options_test.go
- internal/proxy/providers/session_state_test.go
- quickstart/docker-compose.yml
This addresses https://github.com/buzzfeed/sso/issues/40. 
This makes validation of cookie secrets more strict, allowing only for a base64 encoded 32-byte secret. 
Cookie secrets should be able to be created using 
`openssl rand 32 -base64` 
cc @buzzfeed/sso-maintainers
> simplify secret validation

- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
- internal/proxy/proxy_config.go
- internal/proxy/proxy_config_test.go
When pointing the proxy directly at an AWS ALB, e.g., the cert presented by the ALB is guaranteed to be invalid, as you can't get a cert for `*.elb.amazonaws.com`. Depending on your deployment setup you may or may not be able to easily automate creation of corresponding DNS records to match your certs. And of course your certs might be self-signed. Therefore it's desirable to be able to disable TLS verification for upstream servers in some cases. Particularly because the real security barrier is the necessary firewall rule that ensures nothing else can talk to the upstream server.
Fixes #47.
> Make TLS verification of upstream servers configurable

- cmd/sso-auth/main.go
- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
- internal/auth/options.go
- internal/auth/options_test.go
- internal/auth/providers/google.go
- internal/auth/providers/google_test.go
- internal/auth/providers/providers.go
Introduces a simple `switch` to initialize the provider to allow for new providers to be subsequently added.
I did consider removing the `TestGoogleGroupInvalidFile` function and including it in `TestNewOptions`, since it no longer requires a `panic` recovery, but that seemed like maybe the wrong solution once multiple providers are introduced.
Fixes #6.
> Refactor provider options

- .circleci/config.yml
CircleCi failed:
#!/bin/bash -eo pipefail
go get github.com/golang/lint/golint
package github.com/golang/lint/golint: code in directory /go/src/github.com/golang/lint/golint expects import "golang.org/x/lint/golint"
Exited with code 1
bump golint to golang.org/x/lint/golint
> bump golint to golang.org/x/lint/golint

- internal/auth/options.go
- internal/auth/options_test.go
PROXY_ROOT_DOMAIN should be required as documented, as describe here https://github.com/buzzfeed/sso/issues/39
Making that parameter required following the same patter as for others
> Make PROXY_ROOT_DOMAIN required

- internal/proxy/options.go
- internal/proxy/options_test.go
- internal/proxy/providers/provider_data.go
- internal/proxy/providers/sso.go
- internal/proxy/providers/sso_test.go
- quickstart/docker-compose.yml
sso-proxy: adding an optional PROXY_PROVIDER_URL for split dns deployments
addressing: https://github.com/buzzfeed/sso/issues/26
> sso-proxy: adding an optional PROXY_PROVIDER_URL for split dns deployments

- CONTRIBUTING.md
Our `CONTRIBUTING` document did not have merge policy language included.
This PR includes merge policy language to help clarify the way this project is organized and to help contributors and users better understand how contribution works.
N/A
> CONTRIBUTING: added merge policy language

- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
- internal/proxy/options.go
- internal/proxy/options_test.go
I need to do a collateral call to google APIs from my backend to get additional information about the user. For that, I need to have the access token.
Return the access token in the header key `X-Forwarded-AccessToken`.
Let me know if that is a good idea, and I'll make this tests are updated.
> Add access-token in proxy response headers

- CODE_OF_CONDUCT.md
@itwasntandy noticed that our updated CoC contained a placeholder email address. I've created the alias `sso@buzzfeed.com` and updated the docs.
> docs: update email address in CoC

- quickstart/docker-compose.yml
- quickstart/kubernetes/sso-auth-deployment.yml
Cleanup `OLD_COOKIE_SECRET` references, fixes #29.
> quickstart: remove references to OLD_COOKIE_SECRET

- internal/proxy/options.go
- internal/proxy/options_test.go
- internal/proxy/providers/provider_data.go
- internal/proxy/providers/sso.go
- internal/proxy/providers/sso_test.go
- quickstart/docker-compose.yml
- quickstart/kubernetes/sso-proxy-deployment.yml
Dan's [PR](https://github.com/buzzfeed/sso/pull/88) added the ability to have an optional 'internal' host defined that `proxy` will use to connect to `auth`. However, that internal host was only applied on `/redeem` requests. Other cases where `proxy` makes a request to `auth`, like `/refresh`, `/validate`, or `/profile` should also use this internal host if it is provided.
If the optional `PROVIDER_URL_INTERNAL` is set, use that host to connect to `auth` for /redeem, /refresh, /validate, and /profile.
> sso-proxy: internal host should apply to redeem, /refresh, /validate, /profile

- internal/proxy/oauthproxy.go
When running in non https environment (such as in quickstart), the redirect generated by `/signout` is always `https`, so the links are broken.
Use the `cookieSecure` option, as is done in `GetRedirectURL`: https://github.com/buzzfeed/sso/blob/master/internal/proxy/oauthproxy.go#L418
> sso-proxy: sign out redirect URL should use ‘cookieSecure’

- docs/google_provider_setup.md
- docs/sso_config.md
Make the documentation clear that we do not support nested groups in `allowed_groups`. 
In response to #133
> docs: add a note that we do not support nested groups

- Dockerfile
When SSO is deployed with Istio mutual TLS enabled, the normal liveness checks will not work i.e. these:
```
livenessProbe:
httpGet:
path: /ping
port: 4180
scheme: HTTP
readinessProbe:
httpGet:
path: /ping
port: 4180
scheme: HTTP
```
> If mutual TLS is enabled, http and tcp health checks from the kubelet will not work since the kubelet does not have Istio-issued certificates.
Further reading here: https://istio.io/help/faq/security/#k8s-health-checks
The above link suggests using a liveness command, e.g. by installing `curl` and using that instead. `curl` is not currently available in the built image, so this PR adds it.
It would then be possible to use SSO in a cluster with Istio mutual TLS enabled, i.e. the checks can then be changed to
```
livenessProbe:
exec:
command:
- curl
- -f
- …
```
> Add curl to image to help with Istio liveness checks

- README.md
better visibility of attribution for this project from https://github.com/bitly/oauth2_proxy addresses https://github.com/buzzfeed/sso/issues/152
add attribution to our readme
similar to https://github.com/Shadowsocksfork/ShadowsocksFork/blob/master/README.md and https://github.com/bitly/oauth2_proxy/commit/9cf5da7b595a33c00ccf47f85cffa6d7cc89b6ed
> sso: add attribution to our readme

- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
- internal/proxy/options.go
- internal/proxy/proxy_config.go
In dynamic routing environments, upstreams may move IP addresses and intermediate gateways may not gracefully terminate those TCP connections. This is particularly problematic in environments were upstreams may exist on shared infrastructure such as AWS Application Load Balancers.
We need to provide a reset deadline for these TCP connections to rotate them, even if the TCP connections are still active. Unfortunately, to the best of my knowledge, the Go standard library does not provide such dials to rotate active TCP connections after some deadline period.
We implement this logic by lazily rotating the entire HTTP Transport object after deadline intervals expire.
This will create some extra garbage but this should be nominal in most environments.
> sso_proxy: add reset deadline for http transports

- go.mod
- go.sum
- internal/proxy/options.go
- vendor/modules.txt
In #151, a problem was explored where SSO Proxy writes out `200 OK` on long requests but nothing is written out to the client. We were able to trace this issue down to a default configuration we specify for the `http.Server` that would timeout tcp connections after the timeout window specified but before the upstream response was received.
However, because of a bug in the golang stdlib https://github.com/golang/go/issues/21389, when these writes occurred we were unable to easily diagnose the connection had closed and that the write was unsuccessful - no error is returned nor is there any useful log output. 
Unfortunately, there is no way to cleanly handle this error case to make debugging more useful without re-writing portions of the `http.Server`.
For now, we can make this edge case a …
> proxy: set tcp write timeout to max timeout timeout value or default

- internal/auth/authenticator.go
- internal/auth/providers/google.go
- internal/auth/providers/google_test.go
- internal/auth/providers/provider_default.go
- internal/auth/providers/providers.go
- internal/auth/providers/singleflight_middleware.go
- internal/auth/providers/test_provider.go
- internal/proxy/oauthproxy.go
- internal/proxy/providers/providers.go
- internal/proxy/providers/singleflight_middleware.go
- internal/proxy/providers/sso.go
- internal/proxy/providers/sso_test.go
- internal/proxy/providers/test_provider.go
Not all identity providers provide the same API for access groups. This is especially true for Google which has a rather strange mechanism for fetching group information. 
Most identity providers, including Okta, require an individuals access token in order to query information about their groups. However, our abstractions now do not consider this and don't allow for this case.
We pass on the access token now for all identity providers, even if not all identity providers (like Google) require it. This will prove useful and necessary when we get further along for adding access for Okta as an identity provider, which does require it.
> sso: send access token on group information query

- internal/proxy/oauthproxy.go
- internal/proxy/request_signer.go
We received a security report that request signatures do not sign access tokens if the proxy is configured to forward them. These access tokens should be signed by our various signature methods so upstreams can be ensured that these tokens have not tampered via a MITM attack.
> proxy/request signers: request signers should also sign access token

- internal/pkg/logging/logging.go
Our timestamp formatting is incorrect in our logging package. This results in a comically incorrect microsecond time being logged.
In `15:04:05.123`, `1`,`2`,`3` are identifiers being parsed as month, day, and hour respectively.
Fixes https://github.com/buzzfeed/sso/issues/176.
🤦‍♂️
> pkg/logging: resolve timestamp bug

- internal/proxy/oauthproxy.go
Currently, upon refresh of the `Group membership required` error page it changes to a `http: named cookie not present` error page. Related issue: https://github.com/buzzfeed/sso/issues/94
We currently remove the CSRF token from the request after getting and assigning it to a new variable. If, further down the flow the request is found to be invalid for some reason (in this case, the user not being in the required groups) then the relevant error page is given. Upon refresh it tries to grab the CSRF token again however it's no longer part of the request, and so it errors in a less helpful and informative way.
Instead, only clear the CSRF token once we know the request has passed the various checks
> sso-proxy: clear csrf token further down the request flow

- internal/auth/options.go
- internal/auth/providers/google_test.go
- internal/auth/providers/internal_util.go
- internal/auth/providers/internal_util_test.go
- internal/auth/providers/okta.go
- internal/auth/providers/okta_test.go
- internal/auth/providers/provider_default.go
- internal/auth/providers/providers.go
This implements the MVP for adding Okta as an oauth provider for SSO.
Documentation on set up of Okta resources in a separate PR: https://github.com/buzzfeed/sso/pull/182
This PR includes:
- A new Okta provider (based off of the Google provider to keep them consistent where reasonable)
- A set of tests for the Okta provider. Again, initially based off of the Google provider tests however changed/added to where necessary.
- Changes to the options parsing layer to accommodate new settings required. (the only additional env var required that does not have a default is `okta_org_url` which is the URL of the org's okta domain (e.g. test.okta.com))
- Now that we have multiple possible providers, some changes to the `internal_util.go` and it's tests package to separate logic into respective …
> sso: okta provider MVP

- docs/google_provider_setup.md
Nested group support was introduced in https://github.com/buzzfeed/sso/pull/149. The documentation still states this is not supported.
Update the docs to reflect the current functionality.
> docs: update note on nested groups

- Dockerfile
It is best practice to run containers as a non-root user. Currently, the `sso` container runs as root.
Create a non-root user, `sso`, in the image and configure the container to run as this user using the `USER` directive.
> docker: don't run as root

- go.mod
- internal/auth/options.go
- internal/auth/providers/group_cache.go
- internal/auth/providers/group_cache_test.go
- internal/auth/providers/okta.go
- internal/auth/providers/provider_default.go
- internal/auth/providers/providers.go
- internal/auth/providers/singleflight_middleware.go
- internal/auth/providers/test_provider.go
- internal/pkg/groups/localcache.go
- internal/pkg/groups/localcache_test.go
- vendor/golang.org/x/sync/AUTHORS
- vendor/golang.org/x/sync/CONTRIBUTORS
- vendor/golang.org/x/sync/LICENSE
- vendor/golang.org/x/sync/PATENTS
- vendor/golang.org/x/sync/syncmap/map.go
- vendor/modules.txt
- Includes a new module in the `groups` package: **internal/pkg/groups/localcache.go** for local caching of groups.
- Tests included
- A new 'GroupCache' provider which wraps subsequent provider functions, including checks for cached entries using the above 'localcache' for the provider's `ValidateGroupMembership` function.
- Tests included
- Adds a `statsdClient` to the provider interface (and adds/modifies the relevant provider function where necessary)
- New vendored depedency for https://godoc.org/golang.org/x/sync/syncmap
> providers: group caching mechanism for okta provider

- internal/proxy/options.go
See #197 
Add a COOKIE_NAME env var to the option struct
It looks like there are already some tests around custom cookie name values, and I couldn't find any tests based around environment variables I couldn't find any, but if there are some tests needed do let me know!
> Configure Proxy CookieName via Env Var

- internal/proxy/reverse_proxy.go
- internal/proxy/reverse_proxy_test.go
`http.TimeoutHandler` doesn't support request flushing, resulting in any flush interval set being ignored if a timeout is also set (we set a default timeout, but not flush interval, so right now this problem always occurs if a flush interval is set).
https://golang.org/src/net/http/server.go?s=98830:98898#L3129
If a flush interval is set in the upstream config, return the handler without setting a timeout.
> sso_proxy: don't set timeout when flush interval is set

- cmd/sso-auth/main.go
- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
- internal/auth/metrics.go
- internal/auth/metrics_test.go
- internal/auth/mux.go
- internal/auth/mux_test.go
- internal/auth/options.go
- internal/auth/options_test.go
- internal/auth/providers/provider_data.go
- internal/auth/static_files_test.go
- internal/pkg/templates/templates.go
- internal/proxy/options.go
- internal/proxy/options_test.go
- internal/proxy/providers/provider_data.go
- internal/proxy/providers/sso.go
- internal/proxy/providers/sso_test.go
As we move towards supporting multiple providers within `sso-auth`, we need to provide unique callback urls for each identity provider.
We add more provider slug prefixes to url paths and supply a default provider to support unique callback urls as well as preserve backward's compatibility
* Creates a new `AuthenticatorMux` struct to house the mux mechanism for multiple `Authenticators`
* Move initialization from `main.go` to `NewAuthenticatorMux`
* Make `newStatsdClient` public to call from initialization from `main.go`
* Add new `Slug` struct field to `ProviderData` to differentiate between providers.
> sso_auth: add identity provider slug to url path and mux

- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
- internal/auth/mux.go
- internal/auth/mux_test.go
- internal/auth/options.go
After some reflection, we should add configuration for a default identity provider with `sso_auth` to make migrations easier and more seamless.
Add additional configuration for the default provider slug and set up a default identity provider at the path root.
This also fixes `/robots.txt` which is mistakenly left dangling on the idp slug path.
> sso_auth: add default provider slug

- .circleci/config.yml
- .codecov/codecov.yml
- scripts/test
We already try hard to make sure code has appropriate tests written, however we don't currently provide an easy way to monitor and track test coverage.
Integrate the sso repo with a tool like [Codecov](https://codecov.io/), which helps us track and monitor coverage reports and make them a prominent part of pull requests and the contribution workflow.
This currently uses the Codecov [bash uploader](https://docs.codecov.io/v4.3.0/docs/about-the-codecov-bash-uploader) to upload coverage reports, which is one of the recommended methods. Other methods include updating CircleCI to version 2.1 and making use of CircleCI [orbs](https://circleci.com/blog/making-code-coverage-easy-to-see-with-the-codecov-orb/).
Specific settings for codecov to be decided - this PR has been created with defaults.
> ci: integrate with Codecov for test coverage

- internal/auth/middleware.go
- internal/auth/middleware_test.go
Currently, when users try to proxy requests to a root domain (i.e. not a subdomain of the root domain), they receive a 400 response (invalid redirect parameter). I would like to be able to serve content on my root domains in addition to the subdomains.
Allow the literal root domain to be a valid redirect URI.
> [auth] allow proxying root domains

- internal/auth/providers/okta.go
`/oauth2/sign_out` does not currently work with the Okta provider:
> An error occurred during sign out. Please try again.
is returned, and the request to sign the user out is unsuccessful.
This PR adds client authentication for the `Revoke` function (I think this must have been lost during development?), which is used to sign out via the `/oauth2/sign_out` endpoint.
Client authentication is provided using the same method as in the `ValidateSessionState` function: https://github.com/buzzfeed/sso/blob/521ff9c1529f7015d9cdc4d2a75832192535db18/internal/auth/providers/okta.go#L117-L123
> sso_auth: fix client authentication for revoke endpoint

- .codecov/codecov.yml
- README.md
With the recent introduction of codecov, builds are failing to pass checks if their coverage falls below that of master.
- Although we want to _increase_ coverage, I'm not sure if we want to set those hard limitations immediately?
If I understand correctly these changes should remove the 'target', so we'll still get the PR comment but it won't fail due to coverage levels. 
- This also adds the codecov badge to our readme.
> ci: remove minimum coverage setting

- .circleci/config.yml
- Makefile
There is currently no automation around tagging SSO docker images with the `latest` tag.
This PR proposes moving our CircleCI config to use the ‘workflows’ method introduced in CircleCI `2.0`, allowing us to better separate and orchestrate individual jobs.
- Separates circleci jobs into logical ‘workflows’:
- build
- push-sso-dev-commit (only runs if build succeeded, and on each commit)
- push-sso-dev-latest (only runs if build succeeeded, and only on master branch)
- upload-codecov (only runs if build succeeded)
- Makefile tasks:
- new `imagepush-latest` task (pushes with the `latest` tag)
- changes `imagepush` to `imagepush-commit` to help separations for circleci
- adds the `latest` tag to the image in the `releasepush` task.
- We could also separate the build and test steps.
- We …
> ci: introduce circleci workflows

- internal/pkg/sessions/session_state.go
- internal/pkg/sessions/session_state_test.go
- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
- internal/proxy/providers/sso.go
If a user accesses an upstream for which the identity provider has changed, the user will get a very confusing and potentially concerning 500 Internal Server Error.  We can fix this ux flow so the user can be transparently authenticated with the new provider
If a user is are already authenticated, we can transparently re-auth the user by clearing the existing cookie and restarting the authentication flow. If they aren't authenticated, this same process starts new auth flow at the authenticator.
In order to make this work, we must add new fields to the session object which includes what provider slug/type information for the session. This adds some potential length to this cookie which is already starting to get big.
> proxy: transition idps ux flow

- internal/proxy/providers/sso.go
- internal/proxy/providers/sso_test.go
User casing can be inconsistent. For email addresses, changing this casing is probably out the domain of sso. However, SSO effectively owns the notion of the `X-Forwarded-User` and we _can_ make that consistent.
Since the `X-Forwarded-User` is arbitrary to sso, we can normalize the casing.
> sso_proxy: user to lowercase

- .circleci/config.yml
With the introduction of circleci workflows, coverage reports were not being correctly found by the codecov script.
We persist to workspace further down the flow, after the point in which the test coverage file is created. 
The Codecov script appears to exit gracefully to avoid failing builds - we can alter this behaviour with `-Z`:
`-Z           Exit with 1 if not successful. Default will Exit with 0`
> ci: persist workspace further down the flow

- Dockerfile
`httputil.ReverseProxy` doesn't support WebSockets in go 1.11.
Build binaries using go 1.12.
I'm not sure if any additional changes are required to get WebSockets to work, but this is a start.
https://github.com/buzzfeed/sso/issues/103
https://go-review.googlesource.com/c/go/+/146437
> docker: build from go 1.12

- internal/auth/metrics.go
- internal/auth/metrics_test.go
Now that we include a Provider Slug in URL paths, the logic to parse and extract the ‘action’ from the URL incorrectly returns `unknown` for all (most) URL’s.
Expecting a URL path of `/providerSlug/redeem` for example, split the path out based on `/` and test with the last slice item. This manually adds back the `/` (as the split removes it) in order to maintain a notion of URL paths within the overall logic.
Our tests didn’t catch this - would be good to come up with a test that would have caught this.
> sso_auth: fix action tag parsing

- docs/google_provider_setup.md
- docs/okta_provider_setup.md
- docs/quickstart.md
- quickstart/docker-compose.yml
We’ve made some substantial changes to the configuration variables (largely their names, but also what’s optional) required by SSO. This means that the quickstart and other documentation is outdated.
This PR pulls our various documentation back in line with the configuration variables we now use. Most changes are applicable only to the ‘auth’ portion of SSO; the ‘proxy’ configuration variables have not yet been fully updated.
> sso quickstart/docs: update configuration variables

- docs/sso_config.md
- internal/proxy/oauthproxy.go
- internal/proxy/proxy_config.go
- internal/proxy/proxy_config_test.go
* Added InjectRequestHeaders to UpstreamConfig/OptionsConfig
* Loop over InjectRequestHeaders during Authenticate and add headers to the request
#243 
I am unfamiliar with Go and was unsure how to go about testing the actual adding of the headers.  If someone would be kind enough to point me in the right direction I can continue.
> proxy: Allow injection of request headers

- internal/auth/configuration.go
- internal/auth/options.go
If `c.refreshTTL` is not greater than 0 then a panic is caused upon the execution of https://github.com/buzzfeed/sso/blob/9c169b34603a63883f26dc2b717e65df34b0503f/internal/pkg/groups/fillcache.go#L118
At the moment, there's no default for this so it must be explicitly set to avoid a panic.
Set a sane default for `refreshTTL` (this default was removed during the overhaul of configuration options).
> sso_auth: add default for groupcache settings

- docs/google_provider_setup.md
- docs/sso_authenticator_config.md
Right now it's not abundantly clear what environment variables can be set, and in some cases, their types or defaults as well.
Adds a list of environment variables that will be read by sso_auth, their types and defaults. 
Also added is an extra var in the google provider docs
> docs: outline env vars and fix provider setup documentation

- cmd/sso-proxy/main.go
- docs/sso_config.md
- internal/pkg/options/email_address_validator.go
- internal/pkg/options/email_domain_validator.go
- internal/proxy/options.go
- internal/proxy/options_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_config.go
- quickstart/docker-compose.yml
- quickstart/kubernetes/sso-proxy-deployment.yml
Allowed email addresses and domains can only be specified for SSO as a whole, setting the same restriction on all upstreams. It cannot be set on individual upstreams.
Allow these variables to be defined in two separate places:
- in the environment (in the standard 'options' config), acting as a default setting for all upstreams
- within individual upstream configs, overriding the 'default' setting
We still expect one of these to be set and will error if neither are.
Includes small bug fix to both the email address validator and email domain validator packages to avoid mutating the passed in slice, instead opting to create and append to a new one.
> sso_proxy: ability to define allowed email address/domain in upstream config

- internal/auth/authenticator.go
- internal/auth/providers/okta.go
- internal/proxy/oauthproxy.go
- internal/proxy/providers/sso.go
We're not catching the right error within the `oktaRequest` function, causing expired refresh tokens to be categorised under an 'unknown' error type. This results in an unclear and awkward UX in cases where the refresh token has expired. 
Fix the error string we're searching for, and improve the general UX around this error case a little bit to provide users with a sensible error and an option to sign back in. 
The TTL of a refresh token in Okta is easily and commonly customised, whereas the TTL of a refresh token within Google is set at 6 months by default. This has meant we've ran into this error a little bit more frequently with the Okta provider which is why we're fleshing out the UX a bit. (This error is generally unseen when the Google provider is being used)
> sso_*: fix 500 error caused by expired Okta refresh token

- internal/proxy/logging_handler.go
Add support for WebSockets 
What is the proposed solution?
Since we started building on go1.12 with native WebSocket proxy support, the only thing needed is to implement `Hijacker` on `responseLogger` to support WebSockets.
Fixes #103
To proxy WebSocket successfully, an appropriate flush_interval is required. 
This pr is tested to proxy [weave-scope](github.com/weaveworks/scope) with a flush_interval of 0.1s
> sso-proxy: add websocket support

- .circleci/config.yml
- docs/sso_config.md
- go.mod
- go.sum
- internal/proxy/reverse_proxy_test.go
We've recently introduced support for websockets, however we didn't include any tests or documentation updates in the initial pull request.
Add in a couple of simple tests and documentation updates. Also, the docker golang image that CircleCI uses has been updated to `1.12` to bring it in line with SSO's go version (required for websocket support)
> sso_proxy: add test for websockets and update docs

- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
- internal/auth/mux.go
- internal/auth/options.go
- internal/pkg/options/email_address_validator.go
- internal/pkg/options/email_address_validator_test.go
- internal/pkg/options/email_domain_validator.go
- internal/pkg/options/email_domain_validator_test.go
- internal/pkg/options/email_group_validator.go
- internal/pkg/options/mock_validator.go
- internal/pkg/options/validators.go
- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
- internal/proxy/proxy.go
The connection between `AllowedEmailDomains`, `AllowedEmailAddresses`, and `AllowedGroups` is unclear. If all specified, they don't work together well which causes awkward workarounds to be put into place.
Introduce a more structured 'Validator' type within SSO, allowing us to create better and clearer dynamics between these settings (and any other validators that may be added in the future).
There are currently three separate validators: 
- Email Domain
- Email Address
- Email Group
**SSO will now allow the request through providing at least _one_ of these validators pass.**
- I would suggest looking at the following files together: 
```
- internal/pkg/options/validators.go
- internal/pkg/options/email_address_validator.go
- internal/pkg/options/email_domain_validator.go
- …
```
> sso_*: allow simultaneous use of Validators

- .github/release-drafter.yml
Creating and publishing a release right now is a very manual task that can, depending on the amount of merges, take a considerably long time to prepare. 
We'd like to improve this workflow to not only make it less time consuming when releases are worked on, but to help encourage more frequent releases as required by making the overall process _easier_. This change focuses on the actual creation of a release draft.
By using https://github.com/toolmantim/release-drafter, we can largely automate the process of formulating a release draft by having it automatically and continuously populate a draft as and when pull requests are merged.
The draft that this creates is slightly different to what we've been using in the past, however I think this should work fine instead! (it might require some …
> release_drafter: add basic config and template for releases

- internal/pkg/options/email_group_validator.go
- internal/proxy/options.go
- internal/proxy/options_test.go
- internal/proxy/providers/sso.go
- internal/proxy/providers/sso_test.go
- internal/proxy/proxy.go
We require either `allowed_email_addresses` or `allowed_email_domains` to be passed in either as a default or for each upstream, however this limits the usability of email groups as a functional validator. It's difficult to validate a user based on groups alone if you also have to specify email addresses or email domains, for example -- it requires work arounds which should be avoided.
Require `allowed_email_addresses`, `allowed_email_domains` _OR_ `allowed_groups` instead. This means the email group validator can still be used simultaneously with others, but also standalone which allows for a sometimes more expected workflow.
This PR also removes functionality that means if an empty list of groups is passed in to the validator then the user is automatically 'valid' per the group …
> sso_*: allow group validator to be used standalone

- cmd/sso-auth/main.go
- cmd/sso-proxy/main.go
- docs/sso_authenticator_config.md
- go.sum
- internal/auth/configuration.go
- internal/pkg/httpserver/httpserver.go
- internal/pkg/httpserver/httpserver_test.go
- internal/proxy/options.go
Both `sso-proxy` and `sso-auth` abort all in-flight requests on shutdown.  Instead, they should stop accepting new requests and allow in-flight requests to complete before exiting.
Addressing this will make deploys of the sso services less disruptive to end users.
Because graceful shutdown is _just_ tricky enough to get right, here we add a new internal `httpserver` package that exposes a single function, `Run()`, which will run an http server and arrange for graceful shutdown when receiving `SIGTERM` or `SIGINT`.  A shutdown timeout must also be provided, after which the server will abort any outstanding requests.
The easiest way I know to reproduce the behavior uses httpbin via the quickstart:
1. In the quickstart dir, `docker-compose up -d` to bring up the demo services
2. In a …
> cmd: ensure http servers shut down gracefully

- internal/auth/providers/okta.go
- internal/pkg/options/email_domain_validator.go
- internal/proxy/oauthproxy.go
With the validator abstraction work that was recently done we inadvertently started to run group validations for each authenticated request. See 'Notes' section for specific details.
This increased volume of requests increases the potential to cause extra strain on upstream providers
We don't need to validate the groups again here. This pull request brings us closer to previous functionality where we re-validate group membership after refreshing or validating the session, and re-validate email domains and addresses upon each request.
- Now that the group membership check is an official 'validator' within sso-proxy it's ran each time we call `RunValidators()`. 
The problematic call in question: https://github.com/buzzfeed/sso/blob/9019d4f79b453b50882213baa8549d40852daaf7/internal/proxy/oaut …
> sso_proxy: reduce amount of group validations

- Dockerfile
- Makefile
- go.mod
- go.sum
Updates to certain go modules are required. This is starting to cause errors with new builds: https://circleci.com/gh/buzzfeed/sso/2185?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
Running https://github.com/buzzfeed/sso/blob/master/scripts/test locally edited `go.mod` and `go.sum` files as required.
> sso: update go modules

- internal/proxy/request_signer.go
Occasional panics (`http: panic serving 172.17.0.16:49478: d.nx != 0`) which seem to be caused by `sso_proxy` using the same hasher for multiple requests, creating a race condition between the `hasher.Reset()` and `hasher.Write([]byte(repr))` calls.
Instead of storing a `hash.Hash` object within the `RequestSigner`, instead store a function which creates a new `hash.Hash`. This lets each request be signed using a different Hash.
> sso_proxy: fix request signer hash panic

- internal/pkg/groups/fillcache.go
- internal/pkg/groups/fillcache_test.go
- internal/pkg/groups/mock_cache.go
The fillcache package is what we use with the Google (and soon to be Cognito) providers to keep group membership cached. 
Once a request goes through to `sso_auth` to validate a users group membership, the `ValidateGroup` function looks in the local cache for the relevant groups:
https://github.com/buzzfeed/sso/blob/14f2a962d995bbd4b69da4420df5fe53dc3468c2/internal/auth/providers/google.go#L366-L370 
If the group doesn't exist in the cache, it triggers a refresh of the cache which in turn kicks off a goroutine to keep the group cache up to date (based off an input TTL).
Right now, the triggered goroutine only fills the cache _after_ the given TTL, not immediately. Any subsequent calls to `ValidateGroupMembership` between the first call, and the first tick of `ttl` won’t have the groups …
> fillcache pkg: trigger cache update immediately

- go.mod
- go.sum
- internal/auth/providers/google_admin.go
- internal/auth/providers/providers.go
- internal/pkg/groups/fillcache.go
- internal/pkg/groups/fillcache_test.go
Groups aren't actively removed from the fillcache if we find that the group can't be found (based on return codes from the identity provider).
If the group can't be found by the identity provider, then delete it from the fillcache.
> fillcache: remove group from cache if it can't be found by the identity provider

- internal/auth/metrics.go
- internal/auth/metrics_test.go
- internal/proxy/metrics.go
- internal/proxy/metrics_test.go
We send 'request' metrics in various places however they aren't all the same _type_ of metric, which makes things confusing while actually utilising the metrics unless the actual code is inspected.
For example: 
We send these 'request' metrics as time values:
https://github.com/buzzfeed/sso/blob/f302bca23e5b8b841dfb411d3d43df344772e6a6/internal/auth/metrics.go#L69
We send these 'provider.request' metrics as incremented values:
https://github.com/buzzfeed/sso/blob/521ff9c1529f7015d9cdc4d2a75832192535db18/internal/auth/providers/okta.go#L179
Slightly rename the metrics that are of a `time` type so we can easily distinguish between the value types.
This could be classed as a 'breaking' change for anyone using this metric for reporting/monitoring purposes, however not for the actual …
> sso: rename request timing metric

- Dockerfile
- go.mod
- go.sum
- internal/auth/authenticator.go
- internal/auth/mux.go
- internal/auth/static_files_test.go
- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
When proxying to a path with a %-encoded `/` character (i.e. `%2F`), the Golang `http.ServeMux` class auto-unwraps the %-encoding. It then uses `path.Clean()` to "helpfully" normalize successive `/` characters (e.g. `/a/b//c` to `/a/b/c`, `/a/b/../c` to `/a`, etc).
Though admittedly an edge-case, the unintended side-effect is that a URL whose path contains a %-encoded URL will be proxied incorrectly. Fo instance, the URL
`https://example.com/path/http:%2F%2Ffoo.com/`
will be proxied to
`https://example.com/path/http:/foo.com/`.
Replace use of `http.ServeMux` with the `mux.Router` class from the popular https://github.com/gorilla/mux library, which allows use of `URL.EscapedPath()` in lieu of directly reading `URL.Path`. This preserves the %-wrapping of path-components, which in turn …
> Proxy path-components with %-escaped characters in tact.

- internal/proxy/providers/sso.go
- internal/proxy/providers/sso_test.go
See https://github.com/buzzfeed/sso/pull/286
This implements the initial fix described in https://github.com/buzzfeed/sso/pull/286. I think there may be a couple extra edge cases we need to cover in that pull request, so I've pulled out the fix here so it can be applied separately.
> sso_proxy: allow empty slice of groups

- .codecov/codecov.yml
Codecov appears to be incorrectly failing some pull request checks due to the `project` status check. If I understand correctly, our Codecov configuration should mean that the `project` check should fail if the change results in a 2% drop in overall coverage. 
https://github.com/buzzfeed/sso/pull/279 is failing due to a 0.47% drop in project coverage.
It seems the Codecov docs have been updated to show the threshold being set explicitly as a `%`, and some past issues seem to suggest that this may affect how it works, e.g.  https://community.codecov.io/t/threshold-confusion/88. 
It's unclear if this is the cause, but seems sensible to update regardless and to rule it out.
> codecov: update to project threshold to explicit %

- docs/quickstart.md
- internal/auth/configuration.go
- internal/auth/providers/okta.go
[Quickstart](https://github.com/buzzfeed/sso/blob/master/docs/quickstart.md#okta) (and testing in practice) seems to indicate that PROVIDER_*_OKTA_SERVER should be optional, if you wish to use the default okta authorization server.
> If you are not using the default Okta authorization server you will also need to add PROVIDER_OKTAQUICKSTART_SERVER_ID=<okta auth server ID> to the above file.
Make it optional!
> sso_auth: make `provider_*_okta_server` optional

- .circleci/config.yml
- Dockerfile
- go.mod
- internal/proxy/options_test.go
Updates SSO to Go 1.14.
- `internal/proxy/options_test.go`:  quoted error as per 
https://golang.org/doc/go1.14#net/url
> When parsing of a URL fails (for example by Parse or ParseRequestURI), the resulting Error message will now quote the unparsable URL. This provides clearer structure and consistency with other parsing errors.
> sso_*: update to Go 1.14

- internal/proxy/oauthproxy.go
Missing `return` in the `ErrUnauthorizedUpstreamRequested` case within the `Proxy` method
> sso_proxy: add missing return

- docs/sso_config.md
- internal/proxy/options.go
Some documentation for the upstream configuration option `provider_slug`, and the global `sso_proxy` 
`DefaultProviderSlug` option is missing
Add in the missing documentation.
> sso_proxy: document provider slug configs

- cmd/sso-proxy/main.go
- go.mod
- go.sum
- internal/proxy/configuration.go
- internal/proxy/configuration_test.go
- internal/proxy/logging_handler.go
- internal/proxy/metrics.go
- internal/proxy/metrics_test.go
- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
- internal/proxy/options.go
- internal/proxy/options_test.go
- internal/proxy/proxy.go
- internal/proxy/proxy_config.go
- internal/proxy/proxy_test.go
`sso_auth` was migrated to use `go-micro` in https://github.com/buzzfeed/sso/pull/212 to manage variable configuration. `sso_proxy` is still using the original outdated methods and should be updated to also use `go-micro`
Update `sso_proxy` to use `go-micro`. No feature changes are intended to be part of this change, *apart from* the behaviour of the following two variables:
- `SKIP_AUTH_PREFLIGHT` and `PASS_ACCESS_TOKEN` are now **upstream specific** and should be specified as part of upstream configs, **not** global/environment variables.
In general, the patterns used in this pull request are the same ones used in https://github.com/buzzfeed/sso/pull/212
Some notes to support reviewing:
- The bulk of changes here consist of creating the new configuration structure, and altering …
> sso_proxy: update to use `go-micro` for configuration management

- Dockerfile
- cmd/sso-proxy/generate-request-signature/generate_request_signature.go
- docs/generate_request_signature.md
For testing signature validation code in other places, it's nice to be able to easily generate signatures. The prior way of doing this involved setting up a test service, making a request to it, and inspecting the request headers between SSO and the upstream to get the signature.
Make a little command line tool within `sso-proxy` that takes URL, body, and headers to generate a request signature using the `request-signer`.
> sso-proxy: command line tool to generate request signatures

- internal/auth/providers/http_client.go
- internal/proxy/providers/http_client.go
As described in https://github.com/buzzfeed/sso/issues/305, some HTTP clients used in `sso_auth` and `sso_proxy` don't allow for use of `HTTP_PROXY` environment variables -- meaning traffic can't be passed through a proxy if desired.
Make use of the [http.ProxyFromEnvironment](https://golang.org/src/net/http/transport.go?s=16634:16691#L427) method, which allows for usage of these environment variables.
We already make use of this in one HTTP client within `sso_proxy` here: https://github.com/buzzfeed/sso/blob/03e1259e8ce040a5b3937ce684598aa1f9bb980b/internal/proxy/reverse_proxy.go#L53
> sso_auth: use ProxyFromEnvironment in http Transport

- internal/auth/authenticator.go
- internal/auth/authenticator_test.go
- internal/auth/mux.go
- internal/auth/options.go
- internal/pkg/validators/email_address_validator.go
- internal/pkg/validators/email_address_validator_test.go
- internal/pkg/validators/email_domain_validator.go
- internal/pkg/validators/email_domain_validator_test.go
- internal/pkg/validators/email_group_validator.go
- internal/pkg/validators/mock_validator.go
- internal/pkg/validators/validators.go
- internal/proxy/oauthproxy.go
- internal/proxy/oauthproxy_test.go
- internal/proxy/options.go
- internal/proxy/proxy.go
In `internal/pkg/options` we offer a set of tools to help validate sessions. The name of the package, 'options', doesn't fit its responsibility very well, which can contribute to unnecessary confusion while reading through the code.
Separated out from some other cleanups, rename the `options` package to `validators`, and adjust any references to it.
Other pertinent information. Examples: a walkthrough of how the solution might work, why this solution is optimal compared to other possible solutions, or further TODOs beyond this PR.
> sso_*: rename 'options' package to 'validators'

- Makefile
- docs/sso_config.md
- quickstart/docker-compose.yml
- scripts/dist.sh
- Bump versions to `3.0.0` in preparation for new release.
- update various points of documentation with regards to `sso_proxy` [configuration changes](https://github.com/buzzfeed/sso/pull/279)
> sso_*: prepare v3.0.0 release

- quickstart/docker-compose.yml
quickstart is not fully updated with the new variables name introduced with the v3.0.0
rename CLUSTER to UPSTREAM_CLUSTER in sso-proxy
remove CLUSTER from sso-auth. it looks like is not used anymore (https://github.com/buzzfeed/sso/blob/main/internal/auth/configuration.go)
> quickstart - rename CLUSTER to UPSTREAM_CLUSTER

- Dockerfile
`debian:stable-slim` is broken by a repo change but `debian:buster-slim` works
https://www.mail-archive.com/search?l=debian-user@lists.debian.org&q=subject:%22what%27s+wrong+with+my+%5C%22%5C%2Fetc%5C%2Fapt%5C%2Fsources.list%5C%22%5C%3F+Updating+from+such+a+repository+can%27t+be+done+securely%2C+and+is+therefore+disabled+by+default%22&o=newest&f=1
5.1.3. Changed security archive layout
For bullseye, the security suite is now named bullseye-security instead of codename/updates and users should adapt their APT source-list files accordingly when upgrading.
The security line in your APT configuration may look like:
deb https://deb.debian.org/debian-security bullseye-security main contrib
If your APT configuration also involves pinning or APT::Default-Release, it is likely to require …
> sso: fixup for debian bullseye repo changes

- internal/pkg/sessions/session_state.go
- internal/pkg/sessions/session_state_test.go
- internal/proxy/providers/sso.go
In an effort to reduce the scale of some other changes I'm trying to pull through, we make some small refactors here to `internal/proxy/providers/sso.go`.
Included refactors are:
- Pull out the `withinGracePeriod` method within `internal/proxy/providers/sso.go` into a new method within the sessions package: `IsWithinGracePeriod`.
- Instead of calling a local `extendDeadline` function within `internal/proxy/providers/sso.go`, call the already existing sessions package `ExtendDeadline` method.
> sessions pkg: minor refactors

- internal/auth/configuration.go
A typo in `auth/configuration.yml` is preventing `METRICS_STATSD_*` environment variables from being registered, resulting in the default always being used.
mapstruc**true** -> mapstruc**ture** 🥲
> sso_auth: configuration typo

- docs/sso_authenticator_config.md
- docs/sso_proxy_config.md
- internal/pkg/sessions/cookie_store.go
- internal/pkg/sessions/cookie_store_test.go
By default, we set the `Domain` attribute in the session cookie to the request's host value. This causes the cookie to be valid for the provided domain, **and all subdomains**. I don't believe this is expected behaviour, and shouldn't be the default. 
For reference: https://datatracker.ietf.org/doc/html/rfc6265#section-4.1.2.3
> The Domain attribute specifies those hosts to which the cookie will
be sent. For example, if the value of the Domain attribute is
"example.com", the user agent will include the cookie in the Cookie
header when making HTTP requests to example.com, www.example.com, and
www.corp.example.com.
> ...
> If the server omits the Domain attribute, the user
agent will return the cookie only to the origin server.
A leading `.` no longer has any impact on where the cookie is …
> sessions pkg: omit domain attribute in session cookie
